title: Kurzy programovacího jazyka Python
description: Kurzy programovacího jazyka Python

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/tisnik/python-programming-courses"

footer_content: "Copyright &copy; 2019, 2020 Pavel Tisnovsky"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

theme: jekyll-theme-leap-day
